services:
  db:
    image: postgres:latest
    container_name: conduit_database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - conduit_data:/var/lib/postgresql

  frontend:
    build:
      context: ./conduit-frontend
      dockerfile: ../docker/frontend/frontend.Dockerfile

    ports:
      - '4200:4200'

  backend:
    build:
      context: ./conduit-backend
      dockerfile: ../docker/backend/backend.Dockerfile

    ports:
      - '8000:8000'

    depends_on:
      - db

volumes:
  conduit_data:
