services:
  db:
    image: postgres:18.4
    container_name: conduit_database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - conduit_data:/var/lib/postgresql

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/frontend.Dockerfile

    ports:
      - '${FE_PORT}:8080'

    volumes:
      - conduit_staticfiles:/usr/share/nginx/html/static

    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/backend.Dockerfile

    env_file: .env

    expose:
      - '8000'

    volumes:
      - conduit_staticfiles:/static

    depends_on:
      - db

volumes:
  conduit_data:
  conduit_staticfiles:
